### PR TITLE
Added Contact me form and Social links

### PR DESCRIPTION
**Pull request by Chayan-19**
This PR (referring to issue #4 ) adds a contact form (powered by [formspree](https://formspree.io/)) and social links. A few screenshots are attached below.

image

image

## Please, go through these steps before you submit a PR.

- [x] You've explained what the Pull Request is adding.
- [x] You've explained why this is important.

### CODE REVIEW

**Comment by ayushmaang** [comment]
Again with this one, just add more context.

**Comment by Chayan-19** [comment]
> Again with this one, just add more context.

Hey @ayushmaang I've made the requested changes in the PR message. Can you please have a look?

**Comment by ayushmaang** [comment]
Hey this has some merge conflicts. Ping me when you fix em.

**Comment by ayushmaang** [comment]
Merge conflicts here.

**Pull request closed without merging**
